[OidcClient] add a method to fetch introspection URL
Drenso/symfony-oidc pull request #69
Opened 2024-09-06 13:07 UTC by David-Dadon

Our company need to fetch information from the introspection

2024-09-06 14:04 UTC, bobvandevijver requested changes
Thank you for your MR and work so far! I have made some comments so it can make a great and complete addition for this library. Do you think you can work with them?

2024-09-06 14:04 UTC, bobvandevijver commented on src/OidcClient.php
> +    return $data;
I'd like to see a model for this, as the response from the introspection endpoint is strictly defined: https://datatracker.ietf.org/doc/html/rfc7662#section-2.2. 

Best is something similar to the OidcUserData model.

2024-09-06 14:04 UTC, bobvandevijver commented on src/OidcClientInterface.php
> +   */
```suggestion
  /**
   * Introspect the supplied token
   *
   * @throws OidcException
   */
```

2024-09-06 14:04 UTC, bobvandevijver commented on src/OidcClient.php
> +      $this->getConfigurationValue('introspection_endpoint'),
Please create a `getIntrospectionEndpoint` method to be consistent with the other endpoint retrievals.

2024-09-09 11:59 UTC, David-Dadon commented
Hi, I made some corrections after your review of my MR
Best regards

2024-09-10 07:18 UTC, bobvandevijver approved these changes

2024-09-10 07:18 UTC, bobvandevijver commented on src/OidcClient.php
> +    }
```suggestion
    $params = match ($tokenType) {
      OidcTokenType::ACCESS => [
        'token' => $tokens->getAccessToken(),
        'token_type_hint' => 'access_token',
      ],
      OidcTokenType::REFRESH => [
        'token' => $tokens->getRefreshToken(),
        'token_type_hint' => 'refresh_token',
      ],
      default => throw new InvalidArgumentException('Only access and refresh tokens can be introspected'),
    }
```

2024-09-10 07:24 UTC, bobvandevijver commented
Merged with 3ab815a166cc4872d308e1c5f45727905520ded6, thank you!

2024-09-10 07:24 UTC, closed without merging

2024-09-10 07:58 UTC, David-Dadon commented
So fast, thank so much, also for your advices